#! /usr/bin/bash

# Function to check if a directory exists
check_directory_exists() {
  if [ -d "$1" ]; then
    return 0 # Directory exists
  else
    return 1 # Directory does not exist
  fi
}

# Initialize nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

echo "Running autograder..."
cd /autograder/source

# Copy submission files
if ! check_directory_exists "/autograder/submission/source"; then
  # Print error message to standard error
  echo "Error: Student did not submit their assignment properly." >&2
  # Copy the missing_files.json file to the results directory
  cp results/missing_files.json /autograder/results/results.json
  exit 1 # Exit script with an error status
fi
cp -r /autograder/submission/source /autograder/source
echo "Files copied successfully."

# Visit the student's directory and install modules
cd source
npm install

# Run tests
node tests/tests.js

# TODO: Add playwrite tests as well

echo "🔥 Done"
